chore: esp-hal-common - update embedded-hal rc
esp-rs/esp-hal pull request #1051
Opened 2023-12-23 14:47 UTC by elpiel

### Must

- [ ] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [ ] `cargo fmt` was run.
- [ ] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

2023-12-25 17:12 UTC, reitermarkus requested changes

2023-12-25 17:12 UTC, reitermarkus commented on esp-hal-common/src/gpio.rs
>          let inner = &self.inner;
```suggestion
        let inner = &mut self.inner;
```

2023-12-25 17:12 UTC, reitermarkus commented on esp-hal-common/src/gpio.rs
>          let inner = &self.inner;
```suggestion
        let inner = &mut self.inner;
```

2023-12-25 17:12 UTC, reitermarkus commented on esp-hal-common/src/gpio.rs
>          let inner = &self.inner;
```suggestion
        let inner = &mut self.inner;
```

2023-12-25 17:12 UTC, reitermarkus commented on esp-hal-common/src/gpio.rs
>          let inner = &self.inner;
```suggestion
        let inner = &mut self.inner;
```

2024-01-11 15:27 UTC, jessebraham commented
I've taken care of this in #1068, thanks anyway though!

2024-01-11 15:27 UTC, closed without merging