Update embassy to its embedded-* v1.0.0 versions
esp-rs/esp-hal pull request #1076
Opened 2024-01-12 01:28 UTC by Sycrosity

I have not yet had time to test all the examples, but most seem to function as expected.

### Must

- [ ] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [X] `cargo fmt` was run.
- [X] Your changes were added to the `CHANGELOG.md` in the proper section.
- [X] You updated existing examples or added examples (if applicable).
- [X] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [X] You added proper docs for your newly added features and code.

2024-01-12 13:38 UTC, jessebraham commented
Thanks for this, would you mind removing all the patches for the `embassy-*` deps from the Cargo manifests as well, please?

2024-01-13 01:45 UTC, Sycrosity commented
> Thanks for this, would you mind removing all the patches for the `embassy-*` deps from the Cargo manifests as well, please?

@jessebraham this should now be complete, thanks for pointing this out!

2024-01-13 15:53 UTC, bugadani commented
At this time, should the HAL itself depend on embassy-time? I believe the only remaining uses should be examples only?

2024-01-14 23:48 UTC, ProfFan commented
> Update: embassy_multiprio does not work as of yet. All other embassy examples function as expected.

Is this still the case? Do you have a description of what does not work?

2024-01-15 09:46 UTC, bjoernQ commented
> > Update: embassy_multiprio does not work as of yet. All other embassy examples function as expected.
> 
> Is this still the case? Do you have a description of what does not work?

I think those example have their own problems not really to be addressed in this PR: https://github.com/esp-rs/esp-hal/issues/1080

2024-01-15 09:50 UTC, bjoernQ commented
Seems there are still a few patched dependencies:
```
❯ rg 0027a76
esp-hal-smartled\Cargo.toml
33:embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
34:embassy-futures  = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
35:embassy-sync     = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
36:embassy-time     = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }

esp-hal-common\Cargo.toml
194:embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
195:embassy-futures  = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
196:embassy-sync     = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
197:embassy-time     = { git = "https://github.com/embassy-rs/embassy", rev = "0027a76" }
```

2024-01-15 11:48 UTC, MabezDev requested changes

2024-01-15 11:48 UTC, MabezDev commented on esp-hal-common/Cargo.toml
> +embassy-time         = { version = "0.3.0", optional = true }
```suggestion
```

We should only depend on the embassy-time-driver in the hal crates themselves.

2024-01-15 11:48 UTC, MabezDev commented on esp32-hal/Cargo.toml
> +embassy-time   = { version = "0.3.0",  optional = true }
Move this to a dev-dependencies (and apply to all hals)

2024-01-15 21:02 UTC, Sycrosity commented
> Seems there are still a few patched dependencies:

@bjoernQ These should be gone now.

2024-01-15 22:14 UTC, Sycrosity commented
> > At this point, should the HAL itself depend on embassy-time? I believe the only remaining uses should be examples only?
> 
> I guess yes - good idea! We'll need to remove the `embassy-generic-queue-*` features - the binary crate would need to enable them on their dependency on embassy-time then. Not sure if we should do it in this PR or in a follow up PR

From my testing at least, it is possible to use the `embassy-generic-queue-*` features without the embassy-time dependency - when running: 
```bash
c run --example embassy_hello_world --no-default-features -F embassy,embassy-executor-thread,embassy-time-timg0,embassy-generic-queue-128  -F rt,vectored,xtal-40mhz
```

there are no problems - is there something else I am not aware of preventing this feature?

2024-01-16 11:07 UTC, Sycrosity commented
> Thanks!
> 
> `esp-hal-common` still depends on `embassy-time` which is why `embassy-generic-queue-*` just works.
> 
> It would be good to get rid of that dependency in `esp-hal-common` (and those features) - a user can enable the `embassy-generic-queue-*` feature in their own binary crate on their dependency to `embassy-time`

Oh I see - I hadn't realised that. Would that be best done in another issue/PR instead of this one?

2024-01-16 11:16 UTC, bjoernQ commented
> > Thanks!
> > `esp-hal-common` still depends on `embassy-time` which is why `embassy-generic-queue-*` just works.
> > It would be good to get rid of that dependency in `esp-hal-common` (and those features) - a user can enable the `embassy-generic-queue-*` feature in their own binary crate on their dependency to `embassy-time`
> 
> Oh I see - I hadn't realised that. Would that be best done in another issue/PR instead of this one? Should I undo the commit removing the dependencies from the esp32-*-hal crates, or leave it here regardless?

Doing that in a separate PR would be completely fine for me. The changes to the `esp32*-hal` crates can be kept I guess

2024-01-16 17:20 UTC, jessebraham approved these changes
We can deal with `embassy-time` in another PR yeah, I will be doing some cleanup before the next release anyway so I can probably just take care of it.

LGTM, thanks for taking care of this!

2024-01-16 20:25 UTC, MabezDev approved these changes
LGTM, thanks!

2024-01-16 20:25 UTC, merged