[WIP] Prototype for using buffered uart rx
esp-rs/esp-hal pull request #1202
Opened 2024-02-26 14:10 UTC by t-moe

I would like to get the discussion going on how to best implement (async) uart rx buffering. 

In my usecase the hw fifio of 132 bytes quickly overflows when I receive a lot of data from an LTE modem, while doing other tasks. But in other usecases the hw fifo might be enough, thats why I would let it up to the user to decide whether he wants an additional buffer or not.

What do you think of my approach? 
(Would you like to see a `heapless::blocking_mutex::CriticalSectionMutex<RefCell<..>>` instead of a plain `static mut` to store the buffer? )

2024-02-26 17:30 UTC, MabezDev requested changes
Thanks for the PR!

I am interested in something like this for sure! The FIFO quickly becomes a limiting factor, as you've found :D.

I think in general this is my vision for UART is that there would three distinct modes

* FIFO mode - already implemented
* Buffered mode / interrupt driven mode - A different set of struct(s) completely, which may use existing code, but also contain the buffer in which we use to copy out bytes from the uart interrupts
* DMA mode, the most work but the most efficient and the long term solution for uart

This PR targets buffered/interrupt driven mode, I think that with some changes this is mergable. I would take a look at embassy-stm32's uart module layout for an idea of what I have in mind.

2024-02-26 17:30 UTC, MabezDev commented on esp-hal/src/uart.rs
> +    pub (crate) trait RxBuffer {
Is there any reason to make this a trait over a struct containing a `heapless::Deque`?

2024-02-26 17:30 UTC, MabezDev commented on esp-hal/src/uart.rs
> +        pub fn set_buffer<const N: usize>(&mut self, buffer: &'static mut heapless::Deque<u8, N>)
I don't really managing global state like this tbh, I think this should be managed by the user.

2024-02-28 14:47 UTC, t-moe commented
Thank you for the initial feedback @MabezDev.

I'll take a look at how embassy-stm32 does it. Although it might take a while until I find the time to refactor this, as I have a lot of other, more pressing issues in the queue.

2024-03-13 12:51 UTC, jessebraham commented
I've converted this to a draft for the time being, just to help me with keeping track of things. Please feel free to change it back whenever you feel it's ready for review :)

2024-03-15 19:20 UTC, t-moe commented
I've decided to abandon this project, as I have too many other things pending at the same time... I might pick it up again in fall.

Instead I've disabled the `asnych` feature and added a simple buffered interrupt reader using the excellent [`bbqueue`](https://github.com/jamesmunns/bbqueue) crate. I'll share my code below, for anyone else looking for something similar, until we have a nice solution developed and merged into esp-hal.


<details>
<summary>Buffered interrupt reader for async uart</summary>

```rust
/// This file is in parts a copy of the async part of the uart.rs file from the esp-hal crate
/// The async write part is copied 1:1 from the esp-hal crate
/// The async read part is completely rewritten, and it works as follows:
///
/// The main problem with the esp-hal async rx implementation is that it has no buffer except the hardware fifo of 128 bytes.
/// This means that if the async task is not fast enough to read the data from the hardware fifo, the data will be lost.
///
/// Our new implementation uses a BBBuffer to store the data. The BBBuffer is a lock-free ring buffer, and it is filled directly in the interrupt.
/// In order to not wake up the async task for every byte received, we use a signal to wake up the async task when a frame was completed (by rx timeout or atcmd interrupt).
/// The signal also contains the number of bytes available in the buffer at the time of the frame completion isr and whether there was a hw fifo overflow.
///
/// If the interrupt wants to commit a 2nd frame before the async task has read the first frame, the frames will be merged.
/// As a result, the reader will always read one or multiple complete frames.
use bbqueue::BBBuffer;
use core::convert::Infallible;
use core::marker::PhantomData;
use core::task::Poll;
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::signal::Signal;
use embassy_sync::waitqueue::AtomicWaker;
use embedded_io_async::{ErrorType, Read, Write};
use enumset::{EnumSet, EnumSetType};
use hal::macros::interrupt;
use hal::riscv::_export::critical_section;
use hal::uart::Instance;
use pac::uart0::RegisterBlock;

pub struct AsyncUartTx<T: 'static> {
    _uart: hal::UartTx<'static, T>,
}

pub struct AsyncUartRxBuffer<const N: usize> {
    queue: BBBuffer<N>,
    signal: Signal<CriticalSectionRawMutex, FrameCompleteEvent>,
    producer: Option<Producer<N>>,
}

struct Producer<const N: usize> {
    /// The size of the current, unfinished frame
    frame_size: usize,
    /// The buffer to write to
    producer: bbqueue::Producer<'static, N>,
    /// The signal to inform the async task about new frames
    signal: &'static Signal<CriticalSectionRawMutex, FrameCompleteEvent>,
}

struct Consumer<const N: usize> {
    /// how much we can read from the buffer until we reach the end of the current frame
    remaining: usize,
    /// the buffer to read from
    consumer: bbqueue::Consumer<'static, N>,
    /// the signal to wait for new frames
    signal: &'static Signal<CriticalSectionRawMutex, FrameCompleteEvent>,
}

impl<const N: usize> Consumer<N> {
    fn read_remaining(&mut self, mut buf: &mut [u8]) -> usize {
        let mut written = 0;
        while buf.len() > 0 && self.remaining > 0 {
            let grant = self.consumer.read().unwrap();
            let src_buf = grant.buf();
            let len = src_buf.len().min(buf.len()).min(self.remaining);
            buf[..len].copy_from_slice(&src_buf[..len]);
            grant.release(len);
            self.remaining -= len;
            written += len;
            buf = &mut buf[len..];
        }
        written
    }

    async fn read(&mut self, buf: &mut [u8]) -> usize {
        if self.remaining > 0 {
            return self.read_remaining(buf);
        }

        let event = self.signal.wait().await;

        if event.overflow {
            error!("uart RX fifo overflow");
        }

        self.remaining = event.available;
        self.read_remaining(buf)
    }
}

impl<const N: usize> Producer<N> {
    fn append_from_uart(&mut self, uart: &RegisterBlock, overflow: bool, mut frame_complete: bool) {
        let mut fifo_len = uart.status().read().rxfifo_cnt().bits();
        let mut total_written = 0;
        if fifo_len > 0 {
            while let Ok(mut grant) = self.producer.grant_max_remaining(fifo_len as usize) {
                let mut written = 0;
                let buf = grant.buf();
                while fifo_len > 0 && written < buf.len() {
                    buf[written] = uart.fifo().read().rxfifo_rd_byte().bits();
                    written += 1;
                    fifo_len -= 1;
                }
                grant.commit(written);
                total_written += written;
                if fifo_len == 0 {
                    break;
                }
            }

            if total_written > 0 {
                self.frame_size += total_written;
            } else {
                frame_complete = true;
                // This is not an overflow yet, but it will quickly become one because the next isr that comes is ovf.
                // So we wake the task here, even if the frame is not complete yet
            }
        }

        if overflow || frame_complete {
            // If the async reader has not read the previous frame yet, we merge the frames here, otherwise we publish a new one.
            let mut event = self.signal.try_take().unwrap_or(FrameCompleteEvent { available: 0, overflow: false });
            event.overflow |= overflow;
            event.available += self.frame_size;
            self.frame_size = 0;
            self.signal.signal(event);
        }
    }
}

impl<const N: usize> AsyncUartRxBuffer<N> {
    pub fn new() -> Self {
        let queue = BBBuffer::new();
        let signal = Signal::new();
        Self { queue, signal, producer: None }
    }
}

pub struct AsyncUartRx<T: Instance + 'static, const N: usize> {
    _uart: hal::UartRx<'static, T>,
    consumer: Consumer<N>,
}

impl<T> ErrorType for AsyncUartTx<T> {
    type Error = hal::uart::Error;
}

impl<T: Instance, const N: usize> ErrorType for AsyncUartRx<T, N> {
    type Error = Infallible;
}

impl<T> AsyncUartTx<T> {
    pub fn new(uart: hal::UartTx<'static, T>) -> Self {
        Self { _uart: uart }
    }
}

impl<T: Instance, const N: usize> AsyncUartRx<T, N> {
    /// Create a new async UART receiver
    ///
    /// Before passing the rx half of the uart to this constructor,
    /// please configure rx_fifo_full (`set_rx_fifo_full_threshold`)
    /// and configure at least one of rx_timeout (`set_rx_timeout`) or at_amd (`set_at_cmd`)
    ///
    /// # Arguments
    /// * `uart` - The UART Rx instance.
    /// * `rx_buffer` - The buffer to store the received data
    /// * `process_atcmd` - Process data on at cmd interrupt
    /// * `process_tout` - Process data on rx timeout interrupt
    pub fn new(uart_rx: hal::UartRx<'static, T>, rx_buffer: &'static mut AsyncUartRxBuffer<N>, process_atcmd: bool, process_tout: bool) -> Self {
        assert!(process_atcmd || process_tout);
        let (producer, consumer) = rx_buffer.queue.try_split().unwrap();
        let signal = &rx_buffer.signal;
        rx_buffer.producer.replace(Producer { frame_size: 0, producer, signal });

        critical_section::with(|_| unsafe {
            RX_HANDLERS[T::uart_number()] = Some(rx_buffer.producer.as_mut().unwrap());
        });

        let consumer = Consumer { remaining: 0, consumer, signal };

        T::register_block().int_ena().modify(|_, w| {
            if process_atcmd {
                w.at_cmd_char_det_int_ena().set_bit();
            }
            if process_tout {
                w.rxfifo_tout_int_ena().set_bit();
            }
            w.rxfifo_full_int_ena().set_bit();
            w.rxfifo_ovf_int_ena().set_bit();
            w
        });

        Self { _uart: uart_rx, consumer }
    }
}

impl<T: Instance, const N: usize> Drop for AsyncUartRx<T, N> {
    fn drop(&mut self) {
        critical_ [...]

2024-03-15 19:20 UTC, closed without merging