Add unsafe dma api
esp-rs/esp-hal pull request #1523
Opened 2024-04-29 13:11 UTC by bjoernQ

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

### Pull Request Details 📖

#### Description
Fixes #1512

Bringing back the old clumsy API doesn't seem to be a good solution so this adds unsafe versions of write_dma, read_dma and transfer_dma for SPI master

#### Testing
Tested with https://github.com/bjoernQ/rust-esp32s3-ili9341 and the existing examples

2024-04-29 14:06 UTC, MabezDev commented on esp-hal/src/spi/master.rs
> +        pub fn wait(&mut self) -> Result<(), DmaError> {
Ah flush is blocking, okay this makes sense now. Will flush ever get stuck if a DMA transaction fails?

2024-04-29 15:11 UTC, bjoernQ commented on esp-hal/src/spi/master.rs
> +        pub fn wait(&mut self) -> Result<(), DmaError> {
I tried to get it into an error state and it didn't get stuck. Also, it really seems to be fine to just check `SPI::cmd::usr`

2024-05-02 08:15 UTC, JurajSadel approved these changes
LGTM, thanks!

2024-05-02 14:09 UTC, MabezDev requested changes
I'm not against having this as an API, but I think we should explore what we're trying to solve in https://github.com/esp-rs/esp-hal/issues/1512 first.

2024-05-21 16:36 UTC, jessebraham commented
Marking this as draft for now.

2024-05-22 06:08 UTC, bjoernQ commented
> Marking this as draft for now.

Thanks for reminding me of this. I will close this since we should find a better solution than going unsafe

2024-05-22 06:08 UTC, closed without merging