Add auto-detection feature to `esp-println`
esp-rs/esp-hal pull request #1658
Opened 2024-06-05 07:20 UTC by bjoernQ

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

### Pull Request Details 📖

#### Description
Fixes #1576 

Using the ROM function didn't work for me - `buf_uart_no` was always 0 for me but in general I think using SOF-interrupt-flag is a better way to do what we need here.

I also added a CHANGELOG.md for `esp-println` (but no CI checks for that in this PR)

#### Testing
Running the examples which use `esp-println` should print to UART or Serial-JTAG without reconfiguration (or re-compilation).

2024-06-05 08:50 UTC, JurajSadel approved these changes
LGTM, thanks!
I left a very nitpick comment (sorry) I noticed while reading the docs. Feel free to ignore it.

2024-06-05 08:50 UTC, JurajSadel commented on esp-println/README.md
> +- `no-op`: don't print anything
Sorry for nitpicking, we are not consistent here with upper-case/lower-case and colons.

2024-06-05 09:33 UTC, MabezDev requested changes
Thank you! I think checking the SoF interrupt is much nicer than the ROM function (I think the main reason I went with the ROM function in the stub is that eventually we will also have to detect USB OTG too).

Thanks for adding the changelog too. Would you mind adding esp-println to CI too? After that I think this is ready to go :).

2024-06-05 10:36 UTC, MabezDev approved these changes
Thank you!

2024-06-05 11:01 UTC, merged

2025-10-24 19:48 UTC, snoweuph commented
Maybe a stupid necroposting question, but the changelog pointed to this pull:

What does auto detection have to do with removing support for 8266 ?

2025-10-24 19:51 UTC, bugadani commented
Nothing at all. You can see that 8266 removal is placed under a version that has already been released before this PR.

2025-10-25 22:56 UTC, snoweuph commented
ahh okay, thanks.