Periodic system timer & esp32s2 fixes & edge interrupt fixes
esp-rs/esp-hal pull request #167
Opened 2022-08-24 20:24 UTC by MabezDev

Closes #140 
Partially closes (the systimer part) #123

2022-08-24 20:34 UTC, MabezDev commented
FYI when you run the esp32s2 example you'll notice the TARGET1 & TARGET2 interrupts fire at the same time for each of the respective alarms they are associated with at that level. This is not a bug, but just the nature of the interrupts being edge interrupts instead of level (thankfully they're level based in the c3 & s3).

2022-08-24 21:03 UTC, jessebraham requested changes
Just one little change I'd like please!

2022-08-24 21:03 UTC, jessebraham commented on esp32s2-hal/examples/systimer.rs
Could you add the print statement from the other examples here please?

```suggestion
esp_println::println!("SYSTIMER Current value = {}", SystemTimer::now());
```

2022-08-25 06:30 UTC, bjoernQ commented
Awesome! Didn't test for S2 yet - waiting for the toolchain builds
One minor thing; Maybe we should lower the targets for alarm1 and 2 in the examples since it takes ages to hit them

2022-08-25 08:54 UTC, bjoernQ commented
Also works fine on ESP32-S2 for me 🎉

2022-08-25 08:55 UTC, bjoernQ approved these changes
LGTM - just as mentioned maybe adjusting the examples might be a good idea

2022-08-25 11:03 UTC, bjoernQ approved these changes
LGTM

2022-08-25 14:13 UTC, jessebraham approved these changes
Thanks for making that change, LGTM!

2022-08-25 14:13 UTC, merged