Update module documentation - Part 2
esp-rs/esp-hal pull request #1777
Opened 2024-07-09 15:35 UTC by SergioGasquez

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

### Pull Request Details 📖

#### Description
Follow-up PR of https://github.com/esp-rs/esp-hal/pull/1763

#### Testing
Built the documentation and ran the doc-tests.

2024-07-10 11:57 UTC, playfulFence requested changes
Thanks a lot for taking care of this! Here are some nitpicking in comments, some of them are more like suggestions.

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/otg_fs.rs
> +//! It can operate as either a USB Host or Device, and supports fusll-speed (FS)
Typo here: "fusll-speed" -> "full speed"

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/otg_fs.rs
> +//! - Low-speed (LS) not supported.
"LS not supported" ->  "LS is not supported"

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/hmac.rs
> +//! Visit the [HMAC] example for an example of using the HMAC accelerator.
Maybe we should avoid using two "example" words in a row? (just a nitpick)

Something like: "Visit the [HMAC] example to learn how to use the HMAC accelerator"

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/parl_io.rs
> +//! See the [Parallel IO RX] example for an example of initializing the RX and
Same here ("example")

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/parl_io.rs
> +//! See the [Parallel IO TX] example for an example of initializing the TX and
Same here ("example")

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/reset.rs
> +//! namely CPU Reset, Core Reset, System Reset, and Chip Reset. All reset types
Just a suggestion, feel free to decline: maybe let's put those mods to ``?
(Like `CPU Reset`)

2024-07-10 11:57 UTC, playfulFence commented on esp-hal/src/rng.rs
> +//! by calling the `read` method.
Again, just a suggestion. We can also remind that it implements traits from [rand_core](https://docs.rs/rand_core/0.6.4/rand_core/index.html)

2024-07-10 12:51 UTC, JurajSadel reviewed
I agree with @playfulFence's suggestions, otherwise LGTM, thanks for working on this!

2024-07-11 18:13 UTC, jessebraham approved these changes
One small nitpick but otherwise I think it looks good, thanks!

2024-07-11 18:13 UTC, jessebraham commented on esp-hal/src/i2s.rs
> +//! - Only master mode is supported.
IIRC we also only implement the TDM Phillips audio standard, which should probably be noted here as well

2024-07-12 09:48 UTC, MabezDev approved these changes
Thanks!

2024-07-12 10:03 UTC, merged

2024-07-12 10:08 UTC, playfulFence commented
Thanks a lot for all the changes, LGTM! 
Also sorry, I was AFK for a lunch, so I couldn't approve the changes! 😅