Add Rustls examples
esp-rs/esp-hal pull request #1899
Opened 2024-08-02 12:04 UTC by bjoernQ

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

### Pull Request Details 📖

#### Description
This adds two examples using Rustls (a client and a server) for ESP32, ESP32-S3 and ESP32-C6.

Something I learnt just now is that currently it's impossible to compile Rustls for targets w/o atomics - I opened an issue in the Rustls repo for that. (i.e. it's the usage of `alloc::sync::Arc` in Rustls itself - seems like all the dependencies can be tweaked to use `portable-atomic`)

Given that, I'm not sure if these examples are something we currently want to have in the repo? I am also happy to extract the examples and the supporting code into its own repo in my personal GitHub space fow now otherwise

#### Testing
Running the examples on supported targets

2024-08-02 12:34 UTC, bjoernQ commented
Fixes #1836 

While Rustls will also work on H2 no examples are added for H2

2024-08-02 16:07 UTC, AnthonyGrondin commented
>Given that, I'm not sure if these examples are something we currently want to have in the repo? I am also happy to extract the examples and the supporting code into its own repo in my personal GitHub space fow now otherwise

TLS is the next major part after getting the HAL and drivers running. Many protocols and systems use/require it, especially in IoT development. Now the question lies down to; What is the roadmap?

Should `esp-hal` come with an "official" supported (maintained by the organization) TLS solution,  using either [rustls](https://github.com/rustls/rustls), [embedded-tls](https://github.com/drogue-iot/embedded-tls), [esp-mbedtls](https://github.com/esp-rs/esp-mbedtls), etc. Or should there be an interface like [ESP-TLS](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/protocols/esp_tls.html) to ensure compatibility across multiple TLS providers and libraries. These are discussions pertaining to TLS in general and not specifically rustls.

All three of the above mentionned TLS suites support a different set of features, and compatibility. I believe both Rustls and embedded-tls to be the future of TLS on bare-metal, since they are more lightweight and pure Rust implementation. This should be documented for new users who come across needing to use TLS on bare-metal.

### Rustls
- Pure rust implementation
- Requires `alloc` and atomics
- Supports TLS1.2 and TLS1.3
- Supports both client and server
- Supports mTLS
- Hardware acceleration possible (not currently implemented)

### embedded-tls
- Pure rust implementation, for embedded systems
- Can work without `alloc`
- Only supports TLS 1.3
- Only supports client, doesn't support server yet.
- Supports client certificate authentication
- Hardware acceleration possible (not currently implemented)

### esp-mbedtls
- C library used through Rust FFI
- Doesn't require `alloc`. Requires `malloc(), calloc(), free()` from esp-wifi
- Supports both TLS1.2 and TLS1.3
- Supports both client and server
- Supports mTLS
- Hardware acceleration possible (currently only using hardware RSA)

2024-08-02 16:27 UTC, AnthonyGrondin commented
I can build both examples for `esp32s3`, but they need a custom partition table because they exceed the default 1MB partition size.

2024-08-02 17:21 UTC, bjoernQ commented
I totally agree that TLS is an important topic 

We don't have an official TLS roadmap but I'd say both, Rustls and embedded-tls (both HW accelerated) is something I personally want.

After my vacation I'll look into lifting the atomics requirement for Rustls so it will work on all our targets

2024-08-07 13:22 UTC, MabezDev commented
I've converted to draft until we can support all chips, hopefully it won't take too long to get upstream to allow using portable-atomic :crossed_fingers:

2024-11-13 14:21 UTC, MabezDev commented
Just taking another look at this, maybe we should merge this in it's current state? We know the upstream issue needs to be resolved for the non-atomic targets, but that doesn't mean we can't land support for the atomic's target now, I think?

2024-11-27 10:26 UTC, MabezDev commented
Did you mean to close this, or are you planning on opening a new one?

2024-11-27 10:30 UTC, bjoernQ commented
> Did you mean to close this, or are you planning on opening a new one?

oh - that was a mistake

2025-01-23 11:48 UTC, bjoernQ commented
> Just taking another look at this, maybe we should merge this in it's current state? We know the upstream issue needs to be resolved for the non-atomic targets, but that doesn't mean we can't land support for the atomic's target now, I think?

I remove the `blocked` label and mark this as RfR

2025-01-23 12:17 UTC, MabezDev requested changes
Thanks for looking into this again!

2025-01-23 12:24 UTC, bugadani commented on esp-rustls-provider/src/lib.rs
> +struct ProbablyTrng;
I love the name

2025-01-23 12:25 UTC, bugadani commented on esp-rustls-provider/src/lib.rs
> +pub static TLS13_CHACHA20_POLY1305_SHA256: rustls::SupportedCipherSuite =
Why are these public?

2025-01-23 12:26 UTC, bugadani commented
I only have micronits to pick right now - like the fact that this PR isn't about the examples I think, but the provider crate 🤔 What are the long term plans, are we to provide hardware acceleration through the provider crate, where we can?

2025-01-23 12:38 UTC, bjoernQ commented
> I only have micronits to pick right now - like the fact that this PR isn't about the examples I think, but the provider crate 🤔 What are the long term plans, are we to provide hardware acceleration through the provider crate, where we can?

Good point about the PR title 👍 

Yes - we definitely want to support HW-crypto long-term (it's hidden in a vague sentence in the README - should have written it in the PR description)

2025-01-23 13:51 UTC, bjoernQ commented on esp-rustls-provider/src/lib.rs
> +struct ProbablyTrng;
Me too 😄

2025-01-23 13:51 UTC, bjoernQ commented on esp-rustls-provider/src/lib.rs
> +pub static TLS13_CHACHA20_POLY1305_SHA256: rustls::SupportedCipherSuite =
copy pasted that .. fixed

2025-01-23 13:52 UTC, bjoernQ commented on esp-rustls-provider/README.md
> +## Status
I removed the TODOs here - we shouldn't forget about creating separate issues after the merge (since creating them before is kind of weird?)

2025-01-24 14:02 UTC, MabezDev approved these changes
Thanks for addressing my comments, LGTM.

Please don't forget to file the relevant issues once this is merged :smiley:

2025-03-27 07:18 UTC, bjoernQ commented
Considering the general lack of interest in this I'm considering closing this in favor of https://github.com/RustCrypto/rustls-rustcrypto

As it stands this is (not yet) ESP32 specific so putting effort into the linked crate is a better use of time.

Instead of doing our own thing here we should continue to make our crypto accelerators a "drop in" replacement for RustCrypto (i.e. implementing the needed traits) and try to land PRs to make use of alternative implementation in the respective crates

If no one sees any reason to not do what I outlined above I will close this in a few days

2025-03-27 09:23 UTC, Dominaezzz commented
fwiw, I did try reviewing this a few times but there was just too much I didn't understand.
Otherwise I'd love to just slap a green tick on it and ship it 😅

2025-03-27 15:38 UTC, bjoernQ commented
> I'd be curious what's the binary size and memory consumption, compared to: https://github.com/esp-rs/esp-mbedtls

esp-medtls is definitely more light-weight

For the binary size (haven't measured RAM usage)
client: 1335168
server:  1205600

Don't remember the binary sizes of the esp-mbedtls examples but IIRC they are slightly smaller

2025-03-27 15:46 UTC, AnthonyGrondin commented
> > I'd be curious what's the binary size and memory consumption, compared to: https://github.com/esp-rs/esp-mbedtls
> 
> esp-medtls is definitely more light-weight
> 
> For the binary size (haven't measured RAM usage) client: 1335168 server: 1205600
> 
> Don't remember the binary sizes of the esp-mbedtls examples but IIRC they are slightly smaller

On https://github.com/esp-rs/esp-mbedtls/pull/73, 

async_server.rs: 894,560 bytes
async_client.rs:  890,768 bytes

2025-03-27 15:53 UTC, bjoernQ commented
Oh that's a lot smaller 👀

2025-03-31 06:44 UTC, bjoernQ commented
For the crypto traits I opened #3311 

We have a general issue about future examples: #2596 - maybe better to add the need for TLS related examples (probably including embedded-tls) there?

2025-04-03 09:13 UTC, bjoernQ commented
I added a comment to the "examples" issue: https://github.com/esp-rs/esp-hal/issues/2596#issuecomment-2774998290

I guess we can close this for now, then?

2025-04-03 09:27 UTC, closed without merging