Add more trait re-exports to prelude module
esp-rs/esp-hal pull request #260
Opened 2022-11-12 09:06 UTC by icedrocket

2022-11-12 16:01 UTC, jessebraham commented
Thanks for the PR.

What was the motivation behind these changes? For example `GpioExt` wasn't exposed because it _shouldn't_ be exposed, the `split()` function is called in `IO::new()`; is there an issue with  this?

2022-11-12 16:18 UTC, icedrocket commented
I just included it because I've seen other crates include it in the prelude module. I'll edit the commit.

2022-11-12 16:20 UTC, icedrocket commented
I just included it because I've seen other crates include it in the prelude module. I'll edit the commit.

2022-11-12 16:36 UTC, icedrocket commented
@jessebraham It seems that the `system` module is not exposed to users in `esp32-hal`, `esp32s2-hal` and `esp32s3-hal`. Is this intentional?

2022-11-12 16:37 UTC, icedrocket commented
@jessebraham It seems that the `system` module is not exposed to the user in `esp32-hal`, `esp32s2-hal` and `esp32s3-hal`. Is this intended?

2022-11-20 12:51 UTC, icedrocket commented
The reason I created this PR is because I discovered that the traits exposed by the prelude module are slightly inconsistent across platforms. For example, `SensExt` is exposed on esp32 and esp32s2 but not on esp32s3. Also, `SarAdcExt` is not exposed on esp32c2 and esp32c3. I guess this was not intended by the developers, so I fixed it and included most of the traits to make it easier to use them.

If there are traits that shouldn't be included in the prelude module, please let me know about those traits or feel free to add a new commit to remove them.

2022-11-22 19:01 UTC, jessebraham requested changes
Sorry for the delay in getting to this, thanks for the contribution. Looks good overall, just a few small changes I'd like to see please!

2022-11-22 19:01 UTC, jessebraham commented on esp-hal-common/src/prelude.rs
> +    #[cfg(not(esp32c2))]
```suggestion
    #[cfg(rmt)]
```
Same as above

2022-11-22 19:01 UTC, jessebraham commented on esp-hal-common/src/prelude.rs
> +        clock::Clock,
```suggestion
        clock::Clock as _esp_hal_clock_Clock,
```
Same as above

2022-11-23 15:24 UTC, merged