Detangle I2C clock calculation
esp-rs/esp-hal pull request #263
Opened 2022-11-16 10:54 UTC by bjoernQ

- fixes ESP32-C2 in release mode
- fixes the MPU6050 init problem (i.e. no workarounds needed anymore)
- makes the I2C clock calculation code readable and easy to compare to ESP-IDF

Closes #230 
Fixes #213

2022-11-16 11:07 UTC, MabezDev requested changes
Just a small change to the wording of a comment and this looks good to go :)

2022-11-16 11:07 UTC, MabezDev commented on esp-hal-common/src/i2c.rs
> +        // NOTE since we always set the filter threshold to 7 we don't need conditional code here
Mind changing "NOTE" to "FIXME" or something like that so we don't forget about it?

2022-11-16 11:23 UTC, MabezDev approved these changes

2022-11-16 11:31 UTC, merged

2025-01-27 13:10 UTC, bjoernQ commented on esp-hal-common/src/i2c.rs
> +        // hardware behaviors.
good question - but it's from here: https://github.com/espressif/esp-idf/blob/c5865270b50529cd32353f588d8a917d89f3dba4/components/hal/esp32c6/include/hal/i2c_ll.h#L110-L112

2025-01-27 13:12 UTC, bugadani commented on esp-hal-common/src/i2c.rs
> +        // hardware behaviors.
thanks 👍