I2c addr
esp-rs/esp-hal pull request #2864
Opened 2024-12-24 11:19 UTC by bjoernQ

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [ ] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

### Pull Request Details 📖

#### Description
- preparation for adding 10 bit addressing mode later without breaking changes
- use an enum to specify the i2c timeout

Fixes #2786

#### Testing
CI

2025-01-06 08:22 UTC, bugadani reviewed
I wish this were 2 PRs but I have comments for both halves :)

2025-01-06 12:53 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +        matches!(self, Timeout::BusCycles(_)) || matches!(self, Timeout::Maximum)
```suggestion
        matches!(self, Timeout::BusCycles(_) | Timeout::Maximum)
```

2025-01-06 12:54 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +trait CheckTimeout {
Any reason you prefer a trait over a plain old function?

2025-01-06 12:59 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +trait CheckTimeout {
just a matter of taste - but no strong preference - it just looks "a bit" nicer at the call site IMHO

2025-01-06 13:34 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +trait CheckTimeout {
I agree on the weird semantics

2025-01-07 08:39 UTC, JurajSadel commented on esp-hal/src/i2c/master/mod.rs
> +            #[cfg(esp32)]
nitpick: Shouldn't those be `cfg_if!` (or `cfg!`) regarding the APIP GUIDELINES?

2025-01-07 08:50 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +            #[cfg(esp32)]
IMHO it looks worse in this case but happy to change is requested

2025-01-07 09:50 UTC, JurajSadel approved these changes
Thanks!

2025-01-07 10:24 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +/// I2C SCL timeout period.
Newer chips have a bunch of different timeouts so we should maybe prefix the name and uses of this one with scl to make it clear what this is related to.

2025-01-07 14:15 UTC, MabezDev commented on esp-hal/src/i2c/master/mod.rs
> +/// I2C SCL timeout period.
Could we not add new timeout methods as an enum variant?

If we can't, I'm not particularly fond of `SclTimeout` as a name - maybe `BusTimeout` is more clear?

2025-01-07 14:21 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +/// I2C SCL timeout period.
We will be able to configure multiple different timeouts at the same time - I guess having separate enums is a good thing.

I agree `SclTimeout` doesn't sound great - happy to change it to `BusTimeout` or any other suggestion

2025-01-08 10:46 UTC, MabezDev requested changes

2025-01-08 10:46 UTC, MabezDev commented on esp-hal/src/i2c/master/mod.rs
> +    pub fn write<A: AddressMode>(&mut self, address: A, buffer: &[u8]) -> Result<(), Error> {
So with this way of doing things, when we add 10bit support, won't this break code like this:

```rust
i2c.write(0xaa /* <- ambiguous type here, could be a u8 or a u16 */, &[])?;
```

2025-01-08 11:02 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +    pub fn write<A: AddressMode>(&mut self, address: A, buffer: &[u8]) -> Result<(), Error> {
We would be able to implement for `i32`[^1] and decide what to do with that. But it would probably be unclear what i32 would represent. Instead, I would recommend implementing AddressMode for `u8` and `TenBit(u16)` instead, not for other numeric types.

[^1]: https://rust.godbolt.org/z/Wfjh7PMMc

2025-01-08 11:23 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +    pub fn write<A: AddressMode>(&mut self, address: A, buffer: &[u8]) -> Result<(), Error> {
oh yeah - we can't have defaults for type parameters on functions :( which would have been an easy solution

> I would recommend implementing AddressMode for u8 and TenBit(u16) instead, not for other numeric types

I like this solution a lot - 10-bit is uncommon enough to have a new-type for it

2025-01-09 13:52 UTC, bugadani requested changes

2025-01-09 13:52 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +    pub trait AddressModeInternal {
I don't understand the need for this. I2cAddress can `impl From` from the possible address types.

2025-01-09 13:52 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +        pub fn as_u8(&self) -> u8 {
Why is this public, and what will happen when we introduce 10-bit addresses?

2025-01-09 14:44 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +    pub trait AddressModeInternal {
idea is that implementing `From` extends the public API surface and we would need to expose the internal enum

2025-01-09 14:48 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +    pub trait AddressModeInternal {
Why is that a problem, since that enum is already marked with a bunch of derives that only make sense if it's public?

2025-01-09 14:54 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +        pub fn as_u8(&self) -> u8 {
can be pub(super) but since it's in a private module doesn't make much difference

10-bit address support will introduce some more changes - we'll probably have to match on the enum and do a few things differently (and will remove this function)

2025-01-09 14:57 UTC, bjoernQ commented on esp-hal/src/i2c/master/mod.rs
> +    pub trait AddressModeInternal {
we can ofc remove the unnecessary derives - we just shouldn't make anything public which doesn't need to

2025-01-14 12:31 UTC, bugadani approved these changes

2025-01-14 12:32 UTC, MabezDev commented on esp-hal/src/i2c/master/mod.rs
> +    pub fn write<A: AddressMode>(&mut self, address: A, buffer: &[u8]) -> Result<(), Error> {
Based on these ideas, what about the following?

* drop the trait (meaning we don't need the private module too)
* Make a public enum `I2cAddress` which has 7 bit and 10 bit variants
* make our public APIs take `Into<I2cAddress>`
* Add a singular `From<u8> for I2cAddress`

Doing it this way means a user can always pass `I2cAddress` directly, but as a convenience, we also allow a single `u8` address.

2025-01-14 13:29 UTC, bugadani commented on esp-hal/src/i2c/master/mod.rs
> +    pub async fn write_read<A: Into<I2cAddress> + Copy>(
If you convert the address first, we don't need the Copy bound.

2025-01-14 13:44 UTC, bugadani approved these changes

2025-01-14 13:46 UTC, MabezDev requested changes
Just the timeout enum rename, and this will be good to go!

2025-01-14 13:59 UTC, MabezDev commented on esp-hal/MIGRATING-0.22.md
> ++ timeout: SclTimeout::BusCycles(10)
Update these too please

2025-01-14 14:15 UTC, MabezDev approved these changes
Thanks!

2025-01-14 14:33 UTC, merged