aes esp32
esp-rs/esp-hal pull request #348
Opened 2023-01-18 16:25 UTC by matrixhead

2023-01-19 07:23 UTC, bjoernQ commented
Already looks good to me! Looking forward to see support for the other chips 👍 Thanks!

2023-01-19 14:50 UTC, jessebraham commented
Thanks for opening this PR! I've just converted this PR to a draft until it's ready, mostly just to help me keep track of things 😁

2023-01-24 06:56 UTC, matrixhead commented
hey guys i updated the commit could you please take a look at that.  @jessebraham @bjoernQ

2023-01-24 08:39 UTC, bjoernQ commented
Great job! Looks good to me!

If you don't mind it would be good to have this rebased on origin/main, then we can enable CI (it won't work otherwise because of the yanked `riscv` crate)

Thanks, again!

2023-01-24 11:06 UTC, bjoernQ commented
@jessebraham this looks good to me and worked when testing locally - what do you think?

2023-01-24 15:54 UTC, jessebraham requested changes
Overall this is looking quite good, thanks for the contribution!

I left one small comment, a bit nit-picky but it's in the interest of keeping things consistent.

This seems to be working for the Xtensa chips, however when I tested the ESP32-C3 it simply printed "done" after the second-stage bootloader output, it never printed the expected 4 lines comparing HW/SW AES.

2023-01-24 15:54 UTC, jessebraham commented on esp-hal-common/src/aes/mod.rs
> +#[cfg_attr(esp32c3, path = "esp32_c3.rs")]
```suggestion
#[cfg_attr(esp32s3, path = "esp32s3.rs")]
#[cfg_attr(esp32s2, path = "esp32s2.rs")]
#[cfg_attr(esp32c3, path = "esp32c3.rs")]
```

Sorry for this, but we do not use underscores in other files like these in the HAL (`esfuse/esp32xx.rs`, `clock/clocks_ll/esp32xx.rs`, etc.), so would you mind please changing these?

2023-01-24 16:25 UTC, bjoernQ commented
> i kind of cheated on that 😬 i couldn't figure out how to get cpu cycles of risc cpus so i just skipped that part, no problem I'll figure it out and make the necessary changes right away 😄

I think it's similar for the SHA example on ESP32-C3 - there we just print the output as hex bytes without a comparison of the CPU cycles - I guess that should be fine

2023-01-24 16:36 UTC, matrixhead commented
> > i kind of cheated on that 😬 i couldn't figure out how to get cpu cycles of risc cpus so i just skipped that part, no problem I'll figure it out and make the necessary changes right away 😄
> 
> I think it's similar for the SHA example on ESP32-C3 - there we just print the output as hex bytes without a comparison of the CPU cycles - I guess that should be fine

yes that's what i referred to when I'm writing this, i tried searching for a way to this and I'm not sure about this can i use [mcycle](https://docs.rs/riscv/latest/riscv/register/mcycle/index.html) for this?

2023-01-24 16:51 UTC, bjoernQ commented
As far as I know MCYCLE isn't supported - maybe `SystemTimer::now()` works for you?

2023-01-24 16:53 UTC, matrixhead commented
> As far as I know MCYCLE isn't supported - maybe `SystemTimer::now()` works for you? (It's not cycles but for comparing SW and HW it should be okay)

okay let me try this.

2023-01-24 18:04 UTC, jessebraham approved these changes
Thanks for making those changes, LGTM!

2023-01-24 18:04 UTC, merged