esp32c3: Add support for booting from MCUboot bootloader
esp-rs/esp-hal pull request #49
Opened 2022-04-12 15:09 UTC by gustavonihei

This PR intends to enable an **esp-hal**-based Rust application to be booted from the **MCUboot bootloader** on **ESP32-C3**.

[MCUboot](https://github.com/mcu-tools/mcuboot) is a secure bootloader solution feature-wise equivalent to the [IDF 2nd stage bootloader](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/startup.html#second-stage-bootloader) (current default bootloader).
You may find more information on the documentation pages for MCUboot and the Espressif port:
https://docs.mcuboot.com/
https://docs.mcuboot.com/readme-espressif.html

## Testing
```bash
$ cd esp32c3-hal
$ cargo build --release --example hello_world
$ ./test_mcuboot.sh ../target/riscv32imc-unknown-none-elf/release/examples/hello_world
```

## Note
Commit https://github.com/esp-rs/esp-hal/commit/7e3882897b58257aee0b7f3fec60cac72784b126 adds the resources for enabling a quick test of the new feature.
It should eventually be dropped.

2022-10-21 14:47 UTC, jessebraham requested changes
Just a couple small comments, otherwise as far as the code is concerned this looks fine to me. @bjoernQ would you mind taking a quick look as well please whenever you get a chance (if you haven't already)?

If you wouldn't mind it would also be nice for there to be a small section in the `README` briefly describing how to build and use this format. This isn't required, so if you're not feeling like doing it that's fine too, but would be appreciated!

2022-10-21 14:55 UTC, jessebraham commented
Tested with the fixes to the linker script and everything is working as expected on my end, so once the review points have been addressed this should be good to merge.

2022-10-24 12:47 UTC, gustavonihei commented on esp32c3-hal/ld/mb-riscv-link.x
> +    (*(.trap.rust));
Fixed, thanks!

2022-10-24 12:48 UTC, gustavonihei commented on esp32c3-hal/Cargo.toml
> +mcuboot           = []
I agree, I've applied the requested change throughout the PR. Thanks!

2022-10-24 20:25 UTC, jessebraham approved these changes
README looks great, thanks! I think we're good to go here, so thank you again for your patience and your continued work on this feature, I look forward to expanding on it in the future!

2022-10-24 20:25 UTC, merged