Async read
esp-rs/esp-hal pull request #615
Opened 2023-06-22 12:19 UTC by alexiionescu

## serial uart `read` for `embassy` `async`

Also fix an issue with async write on large buffers, was panicking with Err Would Block. Discovered when testing reading and echoing back a large reader buffer. 
Tested on ESP32C3 (WROOM) only using a separate project. Examples do not work on riscv at the moment (see issue [#604](https://github.com/esp-rs/esp-hal/issues/604))

I will use this on a separate larger project that requires a serial bridge between PC and a network of ESP32C3 (WROOM) communicating via ESP-NOW. I might revisit it and fix some issues if I find any.

NOTE: `embassy_hal_async` does not have a `Read` trait for `serial,` only `Write` traits, so I could not follow the same implementation pattern as in the write case. The new function is called `read`, not sure if it is Ok, there was not a read function for nb implementation. If you think is to generic, I can change it to `read_async`

### Must

- [x] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [x] You updated existing examples or added examples (if applicable).
- [x] Added examples are checked in CI

### Nice to have

- [x] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

2023-06-23 10:07 UTC, MabezDev requested changes
Thanks for looking into this! This is a good first iteration but I have a few comments I think we should address :).

2023-06-23 10:07 UTC, MabezDev commented on esp-hal-common/src/uart.rs
> -                    self.write_byte(byte).unwrap() // should never fail
Though I can see a failure case with the original code, I don't think this change is correct. I think we should either:

- flush before writing
- read the number of bytes in the FIFO and ensure we only write the number of bytes left in the FIFO initially.

2023-06-23 10:07 UTC, MabezDev commented on esp-hal-common/src/uart.rs
> +        fn write_rxfifo_rd_byte(&mut self, byte: u8) {
With the comment above, I think we can go back to using `self.write`.

2023-06-23 12:56 UTC, alexiionescu commented
> Though I can see a failure case with the original code, I don't think this change is correct. I think we should either:

- flush before writing
- read the number of bytes in the FIFO and ensure we only write the number of bytes left in the FIFO initially. 

With the original function code below panics at byte 170 on debug and byte 131 on release.
```rust
    let test_buf = [0x31; 200];
    embedded_hal_async::serial::Write::write(&mut uart, &test_buf)
        .await
        .unwrap();
```

I did not have to do a new function, indeed. With this function below, any buffer works, even 12800 long buffer. 
Flush does not solve the issue. The FIFO is empty first time.

```rust
async fn write(&mut self, words: &[u8]) -> Result<(), Error> {
            for chunk in words.chunks(UART_FIFO_SIZE as usize) {
                for &byte in chunk {
                    if self.write_byte(byte).is_err() {
                        UartFuture::new(Event::TxFiFoEmpty, self.inner()).await;
                        self.write_byte(byte).unwrap();
                    }
                }
                UartFuture::new(Event::TxFiFoEmpty, self.inner()).await;
            }
            Ok(())
        }
```

2023-06-23 15:01 UTC, MabezDev requested changes
Thanks, nearly there, just a few more little bits to address :)

2023-06-23 15:01 UTC, MabezDev commented on esp32-hal/examples/embassy_serial.rs
> +    /// max READ_BUF_SIZE buffers to receive
```suggestion
    // max READ_BUF_SIZE buffers to receive
```

2023-06-23 15:01 UTC, MabezDev commented on esp32-hal/examples/embassy_serial.rs
> +    /// timeout read
```suggestion
    // timeout read
```

2023-06-23 16:57 UTC, alexiionescu commented on esp32-hal/examples/embassy_serial.rs
> +struct Buffer<const N: usize> {
Yes, I felt that something like this should be already done, but could not find it. Thanks.

2023-06-24 01:25 UTC, alexiionescu commented on esp-hal-common/src/uart.rs
> +        pub async fn read(&mut self, buf: &mut [u8]) -> Result<usize, Error> {
I will also insert an error case Error::ReadBufferFull when provided buffer size is not enough.

2023-06-24 14:52 UTC, closed without merging

2023-06-24 15:46 UTC, MabezDev commented
Did you mean to close this @alexiionescu?

2023-06-24 15:54 UTC, alexiionescu commented
No, I messed up my pull request branch by merging the latest from upstream in order to run the examples. 
Bad Idea !!!
Now I have rebased to the initial commit and staged all my modifications again. After I am done I need to push it again I guess and discard all other changes.
Any better idea what to do in this case?

Also someone has rewrite the examples to use the same type on all examples and I have already merged that changed
```rust
    interrupt::enable(Interrupt::UART0, interrupt::Priority::Priority1).unwrap();
```
I can keep the merging.

2023-06-24 19:10 UTC, alexiionescu commented
I have pushed the commit before the force-push closed. I don't think I can re-open it myself.

2023-06-25 13:55 UTC, alexiionescu commented
I have also pushed my latest changes based on your review. Please let me know If I need to make a new PR or you can re-open this.