Multicore-aware thread-mode executor
esp-rs/esp-hal pull request #723
Opened 2023-08-14 18:03 UTC by bugadani

## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [ ] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [ ] `cargo fmt` was run.
- [ ] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

Early work, nothing to see here yet. We can't implement this in embassy, because there is no cross-core communication possibility in the Xtensa ISA. However, for consistency's sake I've also included non-multicore support (S2), which is basically identical to what's in embassy.

I realized I don't need to doctor embassy for this to work, so I can put up the PR early. It's just less efficient than what will be possible. Very experimental, probably broken, untested and no examples cover it.

2023-08-15 17:22 UTC, bugadani commented
So, I've added an example which immediately deadlocks. The `multicore` example seems to work so I assume the bug is not in the multicore lock, but my executor code. It will be interesting to debug.

2023-08-16 20:15 UTC, bugadani commented
The added examples are now working on ESP32. The commit history could use some cleanup, but the pull request is now ready to be tested.

One quirky thing I experienced is:
It looks like the timers are started when the first alarm is started. This might cause some interesting behavior when one tries to wait for some duration while spinning in a loop, checking `instant.elapsed()`. Since the timer is not yet running, the loop does not terminate. While this is probably very rare, it's not correct either and I think we should start the timebase in `embassy::init` to fix this issue.

2023-08-20 04:53 UTC, bugadani commented
Testing in my project, the interrupt executor currently hangs when I spawn a task on it.

2023-08-22 17:36 UTC, bugadani commented
Who may I curse with this monster? @MabezDev I hope you don't mind if I ping you for a review?

2023-08-24 13:02 UTC, bugadani commented on esp32-hal/Cargo.toml
> +embassy-executor   = { version = "0.2.1", features = ["nightly"] }
Oh dang, good point, I have these features locally.

2023-08-24 13:03 UTC, bugadani commented on esp-hal-common/src/embassy/executor/xtensa/interrupt.rs
> +#[cfg(esp32)]
Thanks. The problem is with these cfgs is that one never knows what exists 👀

2023-08-24 13:07 UTC, MabezDev commented on esp32-hal/Cargo.toml
> +embassy-executor   = { version = "0.2.1", features = ["nightly"] }
Hmm actually I like the idea of the user choosing _without_ having to add the features to esp32XX-hal and esp-hal-common. I guess we just have to document to use `features embassy-executor/integrated-timers` or generic-queue?

2023-08-24 13:09 UTC, bugadani commented on esp32-hal/Cargo.toml
> +embassy-executor   = { version = "0.2.1", features = ["nightly"] }
Huh... IDK about linking errors, as the examples work as is, but good point. I've added this to the common Cargo.toml

2023-08-24 13:10 UTC, MabezDev commented on esp-hal-common/src/embassy/executor/xtensa/interrupt.rs
> +#[cfg(esp32)]
All the symbols come from `esp-hal-common/devices/CHIP/device.toml`, I guess we should document that better  :D. You can even add your own, but is generally discouraged unless there is a good reason to.

2023-08-24 13:15 UTC, jessebraham requested changes

2023-08-24 13:17 UTC, jessebraham commented on esp-hal-common/src/embassy/executor/xtensa/interrupt.rs
> +#[cfg(esp32)]
Based on my experience most people don't seem to ever look at the README or the docs, so I haven't bothered. Guess we can add something, though.

2023-08-24 13:23 UTC, bugadani commented on esp32-hal/examples/embassy_multicore.rs
> +macro_rules! singleton {
Well I might have gone a bit overboard as I replaced _all_ custom `singleton!` macros, but why not 🤣

2023-08-24 13:28 UTC, bugadani commented on esp-hal-common/src/embassy/executor/xtensa/interrupt.rs
> +    // TODO: it would be pretty sweet if we could register our own interrupt handler
I'm not sure about weak linkage, in theory (unless there are details I need to know but don't) we should be able to copy `peripherals::__INTERRUPTS` into RAM, change https://github.com/esp-rs/esp-hal/blob/6c2659f9e4db7fdc1d5431c267b56ec6caa02ebe/esp-hal-common/src/interrupt/xtensa.rs#L440C9-L440C87 to use the copied handlers and roll with that. I do agree that it's not absolutely necessary

2023-08-24 13:32 UTC, bugadani commented
Bleh, global copy-and-replace just made this worse 🤣

2023-08-24 13:39 UTC, bugadani commented
Ok I ended up going all in against `StaticCell<Executor>`, as static cells are unusable anyway after initialization.

2023-08-24 13:41 UTC, bugadani commented on esp-hal-common/src/embassy/executor/xtensa/interrupt.rs
> +#[cfg(esp32)]
I mean this isn't exactly necessary for the average user. Though, maybe a line would be good in the contributors' guide.

2023-08-24 14:26 UTC, MabezDev approved these changes
LGTM, thanks!

2023-08-28 17:05 UTC, jessebraham approved these changes
LGTM, thanks for taking care of this!

2023-08-28 17:05 UTC, merged